
# SEO settings
title: "Ryan's"
title2: "Blog" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Software, engineer, blog, skybet, devops, web, minimalist, security, hack, greenwich"
url: http://razki.github.io/devBlog # site url
baseurl: "/devBlog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ryan Morrison"
  job      : "Software Engineer"
  bio      : "I am a Software Engineer at Sky Betting & Gaming. I graduated from The University of Greenwich with a first class degree in Computer Science."
  thumb    : /images/avatar.png
  email    : contact@ryan.pm
  url      : http://ryan.pm
  github   : http://github.com/razki
  twitter  : http://twitter.com/sbgryan
  linkedin : https://www.linkedin.com/in/ryan-morrison-18114066

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@sbgryan"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
