
# SEO settings
title: "Ryan's"
title2: " Blog" # default: ""
description: "Chatting about Photography, Tech, and travel"
keywords: "Software engineering, blog, minimalist, photography, travel, beer"
url: https://blog.ryan.pm # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io
hp: https://ryan.pm

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ryan Morrison"
  job      : "Software Engineer and Photographer"
  bio      : "Occasionally Blogging. Not always tech related."
  thumb    : /images/avatar.png
  email    : ryan@ryan.pm
  url      : https://blog.ryan.pm
  github   : http://github.com/razki
  linkedin : https://www.linkedin.com/in/rmson/
  instagram: https://instagram.com/speakofthelevel

# social settings
og_locale: "en_GB"
twitter_card: "summary_large_image"
twitter_site: "@speakofthelevel"
twitter_username: "speakofthelevel"

social:
  name: Ryan Morrison
  links:
    - https://twitter.com/speakofthelevel
    - https://www.facebook.com/speakofthelevel
    - https://www.linkedin.com/in/rmson/
    - https://github.com/razki
    - https://instagram.com/speakofthelevel

gems:
  - bourbon
  - jekyll-paginate

plugins:
  - jekyll-seo-tag

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
