
# SEO settings
title: "Ryan's"
title2: " Blog" # default: ""
description: "Occasional Blogging"
keywords: "Software, engineer, blog, skybet, devops, web, minimalist, security, hack, greenwich"
url: http://blog.ryan.pm # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ryan Morrison"
  job      : "Software Engineer"
  bio      : "Occasionally Blogging."
  thumb    : /images/avatar.png
  email    : contact@ryan.pm
  url      : https://blog.ryan.pm
  github   : http://github.com/razki
  twitter  : http://twitter.com/rxnmo
  linkedin : https://www.linkedin.com/in/rmson/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@rxnmo"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
